### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by BearingMe** [newbrainssoft/Frontend-site-grupo#1]
- [ ] Melhorar a responsividade do layout 
- [ ] Ajustar o contraste do nome de usuário do tema dark
- [ ] Fazer a barra de menu
- [ ] Fazer a barra de pesquisa
- [ ] Fazer o menu de usuário
