### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by BearingMe** [newbrainssoft/Frontend-site-grupo#1]
- [ ] criar um logo
- [x] remodelar a barra de navegação
- [ ] criar uma sidebar 
- [x] arrumar o carousel indicator
- [ ] ajustar os NavButtons para se ativar dinamicamente
